name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rust-checks:
    name: Rust checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install taplo-cli
        run: cargo install taplo-cli --locked

      - name: Report versions
        uses: |
          cargo --version
          rustc --version
          taplo --version

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Check Rust formatting
        run: cargo fmt --all -- --check

      - name: Check manifest formatting
        run: taplo fmt --check Cargo.toml

      - name: Check compilation
        run: cargo check --workspace --all-targets

      - name: Run tests
        run: cargo test --workspace --all-targets
